package by.htp.ex.controller.command;

public enum CommandName {
	GO_TO_BASE_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_NEWS_LIST,
	GO_TO_VIEW_NEWS,
	DO_SIGN_IN,
	DO_SIGN_OUT,
	DO_REGISTRATION,
	CHANGE_LOCALE,
	GO_TO_ADD_NEWS,
	DO_ADD_NEWS,
	GO_TO_EDIT_NEWS,
	DO_EDIT_NEWS,
	DO_DELETE_NEWS,
	GO_TO_USERS_LIST,
	GO_TO_PERSONAL_CABINET,
	DO_EDIT_USER_INFO,
	DO_ADD_COMMENT,
	GO_TO_EDIT_COMMENT,
	DO_DELETE_COMMENT,
	DO_EDIT_COMMENT,
	DO_UNBAN_USER,
	NO_COMMAND
}
